apiVersion: v1
kind: Secret
metadata:
  name: movie-booking-secret
  namespace: movie-booking
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/movie
  SPRING_DATASOURCE_USERNAME: movie_user
  SPRING_DATASOURCE_PASSWORD: movie_password
  JWT_SECRET: change-this-jwt-secret-before-production
  JWT_EXPIRATION: "3600000"
