apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: movie-booking
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "movie-booking-app"
        metrics_path: /actuator/prometheus
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - movie-booking
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: movie-booking-app
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http
